# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - dormir

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_69cce2f300ac409099c692d6a598f735 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_a5a64e314949485b9e3e1f860e0f5341 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_69cce2f300ac409099c692d6a598f735 }}/monisis/imagentpfinal:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'dormir'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_2a7c5e2a6d7844a289d66964e47bc8a1 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_69cce2f300ac409099c692d6a598f735 }}/monisis/imagentpfinal:${{ github.sha }}'